language: node_js
node_js:
  - 0.11

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm install
  - npm run webdriver-update
  - npm run webdriver-start > /dev/null &
  - sleep 1 # give server time to start

script:
  - node_modules/.bin/gulp jshint
  - node_modules/.bin/gulp karma
  - node_modules/.bin/gulp build
  - node_modules/.bin/gulp integrationServer > /dev/null &
  - node_modules/.bin/protractor test/protractor.conf.js --browser=firefox
